# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-09 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0005_attachment_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='category',
            field=models.CharField(choices=[('FILE', 'File'), ('INVOICE', 'Invoice'), ('RECEIPT', 'Receipt')], default='FILE', max_length=30),
        ),
    ]
