# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-27 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0006_auto_20180809_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='category',
            field=models.CharField(default='FILE', max_length=30),
        ),
    ]
